### ISSUE TITLE
Installation of Adapter don't work - code 25

### ISSUE THREAD

**Issue by Ilovegym66** [DNAngelX/ioBroker.iOSAppAdapter#8]
Installation of not possible:
`
iobroker url https://github.com/DNAngelX/ioBroker.iOSAppAdapter --debug
install DNAngelX/ioBroker.iOSAppAdapter#c4bb9c68dd1fcd9f5b3f228a0bfb43d3b5c7455b
NPM version: 10.7.0
Installing DNAngelX/ioBroker.iOSAppAdapter#c4bb9c68dd1fcd9f5b3f228a0bfb43d3b5c7455b... (System call)
 
up to date in 22s
 
198 packages are looking for funding
  run `npm fund` for details
 
host.PVE-Iobroker Cannot install DNAngelX/ioBroker.iOSAppAdapter#c4bb9c68dd1fcd9f5b3f228a0bfb43d3b5c7455b: 0

`

**Comment by chris299** [comment]
bei mir geht das auch nicht:
```
$ iobroker url https://github.com/DNAngelX/ioBroker.iOSAppAdapter.git --host HP-EliteDesk-800-G3-DM-35W --debug
install DNAngelX/ioBroker.iOSAppAdapter#c4bb9c68dd1fcd9f5b3f228a0bfb43d3b5c7455b
Installing DNAngelX/ioBroker.iOSAppAdapter#c4bb9c68dd1fcd9f5b3f228a0bfb43d3b5c7455b... (System call)
up to date in 18s
204 packages are looking for funding run `npm fund` for details
host.HP-EliteDesk-800-G3-DM-35W Cannot install DNAngelX/ioBroker.iOSAppAdapter#c4bb9c68dd1fcd9f5b3f228a0bfb43d3b5c7455b: 0
ERROR: Process exited with code 25
```

was meint den Code 25? und welche Abhängigkeiten gibt es sonst? braucht man spezielle andere Versionen?

**Comment by DNAngelX** [comment]
Erstaunlicherweise ist er aber danach trotzdem installiert:

<img width="1319" alt="image" src="https://github.com/DNAngelX/ioBroker.iOSAppAdapter/assets/4883692/ed632c51-ad18-4638-bd34-0bca9d7c3811">

<img width="1318" alt="image" src="https://github.com/DNAngelX/ioBroker.iOSAppAdapter/assets/4883692/232c098f-553b-4d20-aaab-5e06f18893b4">

**Comment by chris299** [comment]
@DNAngelX tatsächlich installiert der so dennoch
